exeam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('about_us/', include('mainapp.urls', namespace='about_us')),
    path('login/', include('mainapp.urls', namespace='login')),
]

mainapp/urls.py
from django.urls import path, include
import mainapp.views as mainapp
app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('about_us/', mainapp.about_us, name='about_us'),
    path('login/', mainapp.login, name='login'),
]

mainapp/models.py
from django.db import models

class Colors(models.Model):
    colors = models.TextField(verbose_name='Цвет')

    def __str__(self):
        return self.colors


    class Meta:
        verbose_name = 'Цвет'
        verbose_name_plural = 'Цвета'

mainapp/views.py
from django.shortcuts import render
from mainapp.models import Colors
import random


def index(request):
    colors = Colors.objects.all()
    context = {
        'page_title': 'Главная',
        'color': random.choice(colors),
    }
    return render(request, 'mainapp/index.html', context)


def about_us(request):
    context = {
        'page_title': 'О нас',
    }
    return render(request, 'mainapp/about_us.html', context)


def login(request):
    context = {
        'page_title': 'Авторизация',
    }
    return render(request, 'mainapp/login.html', context)

mainapp/templates/mainapp/about_us.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <h1 style="text-align: center;">О нас</h1>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="navmenu">

    <ul>
        <li><a href="{% url 'main:index' %}" class="">Главная</a></li>
        <li><a href="{% url 'main:about_us' %}" class="">О нас</a></li>
        <li style="float: right;"><a href="{% url 'main:login' %}">Войти</a></li>
    </ul>

</div>
{% block content %}
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block content %}
<div class="mainindex">
    <div class="maintext">
        {{ color }}
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/login.html
{% extends 'mainapp/base.html' %}
{% block content %}

<div class="container">
	<form method="post">
		<input type="text" name="username" placeholder="Введите логин">
		<input type="password" name="password" placeholder="Введите пароль">
        <br>
		<input type="submit" name="submit" value="ВОЙТИ">
	</form>
</div>


{% endblock %}